### ISSUE TITLE
Install Hexo

### ISSUE THREAD

**Issue by oknoorap** [idjs/idjs.github.io#1]
Gimana @raitucarp @tianp @hellowin

**Comment by tianp** [comment]
Yuk! Ada yang bisa saya bantu?

**Comment by oknoorap** [comment]
di install aja mas 😁

**Comment by anggiaj** [comment]
https://github.com/idjs/idjs.github.io/pull/2

**Comment by oknoorap** [comment]
@anggiaj udah di merge, index htmlnya bisa di hapus hehe?

**Comment by tianp** [comment]
@oknoorap index.html sudah dihapus, tapi waktu diakses kenapa jadi 404 ya?

**Comment by oknoorap** [comment]
@anggiaj gimana ya? biasanya hexo gimana? dikasih CNAME file ya?

**Comment by hellowin** [comment]
dah works, bisa di close @oknoorap?
